FinalWeb/FinalWeb/Controllers/ForBuyerWishListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalWeb.Models;

namespace FinalWeb.Controllers
{
    public class ForBuyerWishListController : Controller
    {
        DecorFinalWebEntities2 db=new DecorFinalWebEntities2();
        //
        // GET: /ForBuyerWishList/
        public ActionResult Index()
        {
            this.GetDefaultData();

            var wishlistProducts = db.Wishlists.Where(x => x.CustomerID == ShippingData.UserID).ToList();
            return View(wishlistProducts);
        }

        //REMOVE ITEM FROM WISHLIST
        public ActionResult Remove(int id)
        {
            db.Wishlists.Remove(db.Wishlists.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        //ADD TO CART WISHLIST
        public ActionResult AddToCart(int id)
        {
            OrderDetail OD = new OrderDetail();

            int pid = db.Wishlists.Find(id).ProductID;
            OD.ProductID = pid;
            int Qty = 1;
            decimal price = db.Products.Find(pid).UnitPrice;
            OD.Quantity = Qty;
            OD.UnitPrice = price;
            OD.TotalAmount = Qty * price;
            OD.Product = db.Products.Find(pid);

            if (ShippingData.items == null)
            {
                ShippingData.items = new List<OrderDetail>();
            }
            ShippingData.items.Add(OD);

            db.Wishlists.Remove(db.Wishlists.Find(id));
            db.SaveChanges();

            return Redirect(TempData["returnURL"].ToString());

        }
    }
}


FinalWeb/FinalWeb/Views/ForBuyerWishList/Index.cshtml
@model IEnumerable<FinalWeb.Models.Wishlist>
@{
        ViewBag.Title = "Index";
}

                      <section id="aa-catg-head-banner">
                          
                          <div class="aa-catg-head-banner-area">
                              <div class="container">
                                  <div class="aa-catg-head-banner-content">
                                      <h2>Wishlist Page</h2>
                                      <ol class="breadcrumb">
                                          <li><a href="index.html">Home</a></li>
                                          <li class="active">Wishlist</li>
                                      </ol>
                                  </div>
                              </div>
                          </div>
                      </section>
                      <!-- / catg header banner section -->
                      <!-- Cart view section -->
                      <section id="cart-view">
                          <div class="container">
                              <div class="row">
                                  <div class="col-md-12">
                                      <div class="cart-view-area">
                                          <div class="cart-view-table aa-wishlist-table">
                                              <form action="">
                                                  <div class="table-responsive">
                                                      <table class="table">
                                                          <thead>
                                                              <tr>
                                                                  <th></th>
                                                                  <th></th>
                                                                  <th>Product</th>
                                                                  <th>Price</th>
                                                                  <th>Stock Status</th>
                                                                  <th></th>
                                                              </tr>
                                                          </thead>
                                                          <tbody>
                                                              @if (Session["username"] != null)
                                                              {
                                                                  foreach (var item in Model)
                                                                  {

                                                                      <tr>
                                                                          <td><a class="remove" href="@Url.Action("Remove", "ForBuyerWishList", new { id=item.WishlistID})"><fa class="fa fa-close"></fa></a></td>
                                                                          <td><a href="#"><img src="@item.Product.ImageURL" alt="@item.Product.AltText"></a></td>
                                                                          <td><a class="aa-cart-title" href="#">@item.Product.Name</a></td>
                                                                          <td>@item.Product.UnitPrice</td>
                                                                          <td>
                                                                              @if (item.Product.UnitInStock > 0)
                                                                              {
                                                                                  <text>In Stock (@item.Product.UnitInStock)</text>
                                                                              }
                                                                              else
                                                                              { <text>Out of Stock (@item.Product.UnitInStock)</text>}
                                                                          </td>
                                                                          <td><a href="@Url.Action("AddToCart", "ForBuyerWishList", new { id=item.WishlistID})" class="aa-add-to-cart-btn">Add To Cart</a></td>
                                                                      </tr>
                                                                  }
                                                              }
                                                              else
                                                              {
                                                                  <text>Please login to view wishlist</text>
                                                              }
                                                          </tbody>
                                                      </table>
                                                  </div>
                                              </form>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </section>
