FinalWeb/FinalWeb/Models/Supplier.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int SupplierID { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}

FinalWeb/FinalWeb/Controllers/SupplierController.cs
using FinalWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;

namespace FinalWeb.Controllers
{
    public class SupplierController : Controller
    {

        DecorFinalWebEntities2 db = new DecorFinalWebEntities2();

        // GET: Supplier
        public ActionResult Index()
        {
            return View(db.Suppliers.ToList());
        }

        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Supplier supp)
        {
            if (ModelState.IsValid)
            {
                db.Suppliers.Add(supp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Edit(int id)
        {
            Supplier supp = db.Suppliers.Single(x => x.SupplierID == id);
            if (supp==null)
            {
                return HttpNotFound();
            }
            return View(supp);
        }

        [HttpPost]
        public ActionResult Edit(Supplier supp)
        {
            if (ModelState.IsValid)
            {
                db.Entry(supp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(supp);
        }

        public ActionResult Details(int id)
        {
            Supplier supp = db.Suppliers.Find(id);
            if (supp == null)
            {
                return HttpNotFound();
            }
            return View(supp);
        }

        public ActionResult Delete(int id)
        {
            Supplier supp = db.Suppliers.Find(id);
            if (supp == null)
            {
                return HttpNotFound();
            }
            return View(supp);
        }

        //Post Delete Confirmed
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Supplier supp = db.Suppliers.Find(id);
            db.Suppliers.Remove(supp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FinalWeb/FinalWeb/Views/Supplier/Create.cshtml
@model FinalWeb.Models.Supplier

@{
    Layout = "~/Views/_AdminLayout.cshtml";
}


@using (Html.BeginForm("Create", "Supplier", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
    
        <div class="col-md-8">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { @class = "form-control" }})
                    @Html.ValidationMessageFor(model => model.ContactName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContactTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContactTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })

                </div>
            </div>




            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div>
                <img src="~/Content/Images/ProfileImage.svg" alt="" class="img-thumbnail" width="160" height="160" />
            </div><br />
            <div>
                <a href="#" class="btn btn-sm btn-primary"> <i class="fa fa-fw fa-folder-open-o"></i> Browse</a>
                <a href="#" class="btn btn-sm btn-danger"> <i class="fa fa-fw fa-remove"></i> Clear</a>
            </div>
        </div>
    </div>
}

FinalWeb/FinalWeb/Views/Supplier/Delete.cshtml
@model FinalWeb.Models.Supplier

@{
    Layout = "~/Views/_AdminLayout.cshtml";
}

<h3>Are you sure you want to delete this?</h3>
<hr />
<div class="row">
    <div class="col-md-8">
        <dl class="dl-horizontal ">
            <dt>
                @Html.DisplayNameFor(model => model.SupplierID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SupplierID)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CompanyName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CompanyName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContactName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContactName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContactTitle)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContactTitle)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Mobile)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Mobile)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Phone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Phone)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.City)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.City)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Country)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Country)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Fax)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Fax)
            </dd>          

        </dl>
    </div>
    <div class="col-md-4">
        <div>
            <img src="~/Content/Images/ProfileImage.svg" alt="" class="img-thumbnail" width="160" height="160" />
        </div>
    </div>
</div> 
    @using (Html.BeginForm("Delete", "Supplier", new { id = @Model.SupplierID }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">            
            @Html.ActionLink("Back to List", "Index", null, new { @class = "" })
            <input type="submit" value="Delete" class="btn btn-danger col-md-offset-1" /> 
        </div>
    }

FinalWeb/FinalWeb/Views/Supplier/Details.cshtml
@model FinalWeb.Models.Supplier

@{
    Layout = "~/Views/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-8">
        <dl class="dl-horizontal ">
            <dt>
                @Html.DisplayNameFor(model => model.SupplierID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SupplierID)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CompanyName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CompanyName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContactName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContactName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContactTitle)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContactTitle)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Mobile)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Mobile)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Phone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Phone)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.City)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.City)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Country)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Country)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Fax)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Fax)
            </dd>     

        </dl>
    </div>
    <div class="col-md-4">
        <div>
            <img src="~/Content/Images/ProfileImage.svg" alt="" class="img-thumbnail" width="160" height="160" />
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

FinalWeb/FinalWeb/Views/Supplier/Edit.cshtml
@model FinalWeb.Models.Supplier

@{
    Layout = "~/Views/_AdminLayout.cshtml";
}


@using (Html.BeginForm("Edit", "Supplier", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.HiddenFor(model=>model.SupplierID)
        <div class="col-md-8">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContactName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContactTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContactTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>  
            <div class="form-group">
                @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                </div>
            </div>  

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address,  new { @class = "form-control" } )
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

                      

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-primary" />
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div>
                <img src="~/Content/Images/ProfileImage.svg" alt="" class="img-thumbnail" width="160" height="160" />
            </div><br />
            <div>
                <a href="#" class="btn btn-sm btn-primary"> <i class="fa fa-fw fa-folder-open-o"></i> Browse</a>
                <a href="#" class="btn btn-sm btn-danger"> <i class="fa fa-fw fa-remove"></i> Clear</a>
            </div>
        </div>
    </div>
}

FinalWeb/FinalWeb/Views/Supplier/Index.cshtml
@model IEnumerable<FinalWeb.Models.Supplier>

@{
    Layout = "~/Views/_AdminLayout.cshtml";
}

<div >
   
    <a href="@Url.Action("Create", "Supplier")" class="btn btn-primary"><i class="fa fa-plus"></i> Add New</a>  
</div>
<br /><br />
<div class="table-responsive ">
    <table class="table table-condensed table-hover table-bordered table-striped table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SupplierID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>            
            
            <th></th>
        </tr>
        @if (Model!=null)
    {

        foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SupplierID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mobile)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                
                <td>
                    <a class="btn btn-sm btn-primary" href="@Url.Action("Edit", "Supplier", new { id = item.SupplierID })" aria-label="Edit">
                        <i class="fa fa-edit" aria-hidden="true"></i>
                    </a>
                    <a class="btn btn-sm btn-info" href="@Url.Action("Details", "Supplier", new { id = item.SupplierID })" aria-label="Details">
                        <i class="fa fa-info" aria-hidden="true"></i>
                    </a>
                    <a class="btn btn-sm btn-danger" href="@Url.Action("Delete", "Supplier", new { id = item.SupplierID })" aria-label="Delete">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        }
    }

    </table>
</div>