FinalWeb/FinalWeb/Controllers/ForBuyerAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalWeb.Models;
using System.Data;
using System.Data.Entity;

namespace FinalWeb.Controllers
{
    public class ForBuyerAccountController : Controller
    {
           DecorFinalWebEntities2 db=new DecorFinalWebEntities2();
        //
        // GET: /ForBuyerAccount/
        public ActionResult Index()
        {
            this.GetDefaultData();

            var usr = db.Customers.Find(ShippingData.UserID);
            return View(usr);
        }
	    
        //REGISTER CUSTOMER
        [HttpPost]
        public ActionResult Register(Customer cust)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(cust);
                db.SaveChanges();

                Session["username"] = cust.UserName;
                ShippingData.UserID = GetUser(cust.UserName).CustomerID;          
                return RedirectToAction("Index","ForBuyerHome");
            }
            return View();
        }

       
       
        //LOG IN
        public ActionResult Login()
        {
            return View();
        }

         [HttpPost]
        public ActionResult Login(FormCollection formColl)
        {
            string usrName = formColl["UserName"];
            string Pass = formColl["Password"];

            if (ModelState.IsValid)
            {
                var cust = (from m in db.Customers
                            where (m.UserName == usrName && m.Password == Pass)
                            select m).SingleOrDefault();

                if (cust !=null )
                {
                    ShippingData.UserID = cust.CustomerID;
                    Session["username"] = cust.UserName;
                    return RedirectToAction("Index", "ForBuyerHome");
                }
                      
            }
            return View();
        }

        //LOG OUT
         public ActionResult Logout()
         {
             Session["username"] = null;
             ShippingData.UserID = 0;
             ShippingData.items = null;
             return RedirectToAction("Index", "UserType");
         }

       

        public Customer GetUser(string _usrName)
        {
            var cust = (from c in db.Customers
                        where c.UserName == _usrName
                        select c).FirstOrDefault();
            return cust;
        }

        //UPDATE CUSTOMER DATA
        [HttpPost]
        public ActionResult Update(Customer cust)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cust).State = EntityState.Modified;
                db.SaveChanges();
                Session["username"] = cust.UserName;
                return RedirectToAction("Index", "ForBuyerHome");
            }
            return View();
        }
    }
}


FinalWeb/FinalWeb/Views/ForBuyerAccount/Login.cshtml

@{
    ViewBag.Title = "Login";
  
}

<section id="aa-myaccount">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-myaccount-area">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="aa-myaccount-login">
                                <h4>Login</h4>

                                @using (Html.BeginForm("Login", "ForBuyerAccount", FormMethod.Post, new { @class = "aa-login-form" }))
                                {
                                    <label for="">Username or Email address<span>*</span></label>
                                    <input name="UserName" type="text" required placeholder="Username">
                                    <label for="">Password<span>*</span></label>
                                    <input name="Password" type="password" required placeholder="Password">
                                    <button type="submit" class="aa-browse-btn" style="background-color:black">Login</button>
                                    <label class="rememberme" for="rememberme"><input type="checkbox" id="rememberme"> Remember me </label>
                                    <p class="aa-lost-password"><a href="#">Forgot your password?</a></p>
                                }

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="aa-myaccount-register">
                                <h4>Register</h4>
                                @using (Html.BeginForm("Register", "ForBuyerAccount", FormMethod.Post, new { @class = "aa-login-form" }))
                                {
                                    <label for="">First Name<span>*</span></label>
                                    <input name="First_Name" type="text" required placeholder="Enter first name">

                                    <label for="">Last Name<span>*</span></label>
                                    <input name="Last_Name" type="text" required placeholder="Enter last name">

                                    <label for="">Username<span>*</span></label>
                                    <input name="UserName" type="text" required placeholder="Username">

                                    <label for="">Password<span>*</span></label>
                                    <input name="Password" type="password" required placeholder="Password">

                                    <label for="">Email<span>*</span></label>
                                    <input name="Email" type="text" required placeholder="Enter your email">

                                    <label for="">Mobile<span>*</span></label>
                                    <input name="Mobile1" type="text" required placeholder="Mobile">

                                    <label for="">Address<span></span></label>
                                    <input name="Address1" type="text" required placeholder="Address">

                                    <button type="submit" class="aa-browse-btn" style="background-color:black">Register</button>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- / Cart view section -->

